import { BreadType } from "../bt.types";

export const breadRecipes = [
    {
        kind: BreadType.Croissant,
        flour: 41.7,
        yeast: 0.8,
        salt: 0.8,
        butter: 25.0,
        sugar: 4.2,
        milk: 8.3,
        redBeanPaste: 0.0,
        malt: 0.0,
    },
    {
        kind: BreadType.Anpan,
        flour: 50.0,
        yeast: 0.9,
        salt: 1.0,
        butter: 3.8,
        sugar: 6.3,
        milk: 12.5,
        redBeanPaste: 25.0,
        malt: 0.0,
    },
    {
        kind: BreadType.Begguette,
        flour: 500.0,
        yeast: 5.0,
        salt: 10.0,
        butter: 0.0,
        sugar: 0.0,
        milk: 0.0,
        redBeanPaste: 0.0,
        malt: 10.0,
    },
    {
        kind: BreadType.Begal,
        flour: 62.5,
        yeast: 0.9,
        salt: 1.3,
        butter: 0.0,
        sugar: 1.3,
        milk: 0.0,
        redBeanPaste: 0.0,
        malt: 1.9,
    },
    {
        kind: BreadType.Ciabatta,
        flour: 400.0,
        yeast: 4.0,
        salt: 8.0,
        butter: 0.0,
        sugar: 0.0,
        milk: 0.0,
        redBeanPaste: 0.0,
        malt: 0.0,
    },
    {
        kind: BreadType.Naan,
        flour: 60.0,
        yeast: 1.0,
        salt: 0.5,
        butter: 2.0,
        sugar: 3.0,
        milk: 10.0,
        redBeanPaste: 0.0,
        malt: 0.0,
    },
];
